#!/bin/sh
export HOME={{pkg.svc_data_path}}
cd {{pkg.svc_path}}

if [ "$(whoami)" = "root" ]; then
  exec chpst \
    -U hab:hab \
    -u hab:hab \
    python -m flask run --host={{cfg.host}} --port={{cfg.port}} 2>&1
else
  exec python -m flask run --host={{cfg.host}} --port={{cfg.port}} 2>&1
fi
